INSERT INTO public.pranks ("name",description,default_jeton_cost_equivalent,xp_reward_executor,xp_reward_target,coins_reward_executor,coins_reward_target,"type",config_details_json,requires_proof,is_active,created_at,image_url,rarity) VALUES
	 ('Min Brightness Stealth','Is the screen even on? It''s so dark!',5,3,1,0,0,'declarative'::public."prank_type_enum",'{"brightness_level": "min"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (6).png','common'::public."prank_rarity_enum"),
	 ('Silly Animal Ringtone','BAA! Incoming call! (Changes ringtone to a goat scream or similar).',6,4,2,1,0,'declarative'::public."prank_type_enum",'{"ringtone_sound": "goat_scream"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (7).png','common'::public."prank_rarity_enum"),
	 ('Wi-Fi Amnesia','Why won''t my phone connect to Wi-Fi anymore? (Forgets a key Wi-Fi network).',7,4,2,0,0,'declarative'::public."prank_type_enum",'{"wifi_action": "forget_network"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (9).png','common'::public."prank_rarity_enum"),
	 ('Potato Phone Nickname','My device is now officially a "Potato Phone" (Changes phone name in settings).',5,3,1,0,0,'declarative'::public."prank_type_enum",'{"new_phone_name": "Potato Phone"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (10).png','common'::public."prank_rarity_enum"),
	 ('Ghost Voicemail','You have one new (non-existent) voicemail!',4,2,1,0,0,'notification_spam'::public."prank_type_enum",'{"notification_type": "fake_voicemail"}',false,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (11).png','common'::public."prank_rarity_enum"),
	 ('Quick Screen Timeout','The screen keeps turning off so fast! (Sets screen timeout to 15 seconds).',6,4,2,1,0,'declarative'::public."prank_type_enum",'{"screen_timeout": "15s"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (12).png','common'::public."prank_rarity_enum"),
	 ('Inverted Colors Flash','Whoa, all the colors are flipped and psychedelic! (Inverts screen colors).',7,4,2,1,0,'declarative'::public."prank_type_enum",'{"screen_effect": "invert_colors"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (13).png','common'::public."prank_rarity_enum"),
	 ('Do Not Disturb On','Why am I not getting any notifications? (Turns Do Not Disturb On).',8,5,2,1,0,'declarative'::public."prank_type_enum",'{"toggle_setting": "dnd_on"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (14).png','common'::public."prank_rarity_enum"),
	 ('Imaginary Fish Feeding Reminder','Don''t forget to feed Bubbles! (Adds a recurring fake calendar event).',5,3,1,0,0,'declarative'::public."prank_type_enum",'{"recurrence": "daily", "calendar_event": "Feed imaginary fish"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (15).png','common'::public."prank_rarity_enum"),
	 ('Vague Emoji Barrage','What could 👽🤷‍♂️🍕 possibly mean? (Sends a series of cryptic emojis).',4,2,1,0,0,'declarative'::public."prank_type_enum",'{"message_content": "👽🤷‍♂️🍕✨"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (16).png','common'::public."prank_rarity_enum");
INSERT INTO public.pranks ("name",description,default_jeton_cost_equivalent,xp_reward_executor,xp_reward_target,coins_reward_executor,coins_reward_target,"type",config_details_json,requires_proof,is_active,created_at,image_url,rarity) VALUES
	 ('Clock Format Flip','Is it 2 PM or 14:00? (Switches between 12-hr and 24-hr clock format).',5,3,1,0,0,'declarative'::public."prank_type_enum",'{"clock_format_action": "toggle"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (17).png','common'::public."prank_rarity_enum"),
	 ('Instagram Blockade (Temporary)','Instagram won''t load! The horror! (Simulates app block or guides user to temp block it).',25,15,5,5,2,'declarative'::public."prank_type_enum",'{"app_to_block": "Instagram", "duration_minutes": 5}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (1).png','rare'::public."prank_rarity_enum"),
	 ('Monochrome Mode','Everything''s suddenly black and white, like an old movie! (Turns screen to monochrome)',8,5,2,1,0,'declarative'::public."prank_type_enum",'{"screen_effect": "monochrome"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (2).png','common'::public."prank_rarity_enum"),
	 ('Contact Name Anarchy','Why is ''The Supreme Overlord'' calling me? (Changes one important contact name).',30,18,6,6,2,'declarative'::public."prank_type_enum",'{"contact_to_edit": "Mom|Dad|Boss", "new_name_options": ["The Supreme Overlord", "My Humble Servant"]}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (3).png','rare'::public."prank_rarity_enum"),
	 ('Alarm Symphony of Annoyance','The symphony of never-ending alarms (Sets 5 alarms for slightly different, annoying times).',35,20,7,7,3,'declarative'::public."prank_type_enum",'{"alarm_count": 5, "alarm_interval_minutes": 1, "start_time_offset_minutes": 1}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (4).png','rare'::public."prank_rarity_enum"),
	 ('Autocorrect Rebellion','My phone has a mind of its own when I type (Autocorrects "yes" to "maybe, I guess?" and "no" to "absolutely, positively!").',40,22,8,8,3,'declarative'::public."prank_type_enum",'{"autocorrect_maps": [{"to": "maybe, I guess?", "from": "yes"}, {"to": "absolutely, positively!", "from": "no"}]}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (5).png','rare'::public."prank_rarity_enum"),
	 ('Prankster Wallpaper Takeover','Surprise! My face is your new background (Changes wallpaper to a goofy photo of the prankster).',25,15,5,5,2,'declarative'::public."prank_type_enum",'{"wallpaper_type": "prankster_face"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (6).png','rare'::public."prank_rarity_enum"),
	 ('Giant Text Mode','EVERYTHING IS SO BIG NOW! (Turns on "Large Text" or max font size).',20,12,4,4,1,'declarative'::public."prank_type_enum",'{"font_size": "max"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (7).png','rare'::public."prank_rarity_enum"),
	 ('Rubber Duck Browser Invasion','Why are there so many ducks on my internet? (Opens 20 browser tabs of rubber ducks).',30,18,6,6,2,'declarative'::public."prank_type_enum",'{"tab_count": 20, "browser_tabs_url": "search_images_rubber_duck"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (8).png','rare'::public."prank_rarity_enum"),
	 ('Fake Celebrity Call','OMG! [Celebrity Name] is calling me?! (Not really) (Simulates incoming call screen).',35,20,7,7,3,'declarative'::public."prank_type_enum",'{"caller_name_options": ["Ryan Reynolds", "Zendaya", "Local Mayor"]}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (9).png','rare'::public."prank_rarity_enum");
INSERT INTO public.pranks ("name",description,default_jeton_cost_equivalent,xp_reward_executor,xp_reward_target,coins_reward_executor,coins_reward_target,"type",config_details_json,requires_proof,is_active,created_at,image_url,rarity) VALUES
	 ('Ominous Lock Screen Message','Lock screen message changed to "I Know Your Wi-Fi Password".',25,15,5,5,2,'declarative'::public."prank_type_enum",'{"lock_screen_message": "I Know Your Wi-Fi Password 👀"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (10).png','rare'::public."prank_rarity_enum"),
	 ('Useless App Icon','This new app doesn''t seem to work... (Creates a fake app icon that does nothing or opens a funny image).',28,16,5,5,2,'declarative'::public."prank_type_enum",'{"fake_app_name": "Super Secret Tool", "action_on_open": "rickroll_image"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (11).png','rare'::public."prank_rarity_enum"),
	 ('Extreme Cuteness Weather Alert','Warning: Dangerously high levels of adorable in your area (Sends fake weather alert).',22,14,4,4,1,'notification_spam'::public."prank_type_enum",'{"alert_body": "Extreme levels of adorable puppies detected in your vicinity. Proceed with caution (and squeals).", "alert_title": "Cuteness Overload Warning"}',false,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (12).png','rare'::public."prank_rarity_enum"),
	 ('Phantom Low Battery','Panic! My battery is dying at 1%... or is it? (Sends fake low battery notification).',20,12,4,4,1,'notification_spam'::public."prank_type_enum",'{"notification_body": "1% remaining. Connect charger immediately.", "notification_title": "Battery Critically Low"}',false,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (2).png','rare'::public."prank_rarity_enum"),
	 ('Max Brightness Attack','Suddenly, the phone screen is blindingly bright.',5,3,1,0,0,'declarative'::public."prank_type_enum",'{"brightness_level": "max"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (5).png','common'::public."prank_rarity_enum"),
	 ('Cracked Screen Wallpaper','Oops! Looks like the screen is shattered (it''s just a picture for the wallpaper).',7,4,2,1,0,'declarative'::public."prank_type_enum",'{"wallpaper_type": "cracked_screen"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (4).png','common'::public."prank_rarity_enum"),
	 ('Airplane Mode Surprise','No signal? What happened to the internet? (Toggles Airplane Mode on).',8,5,2,1,0,'declarative'::public."prank_type_enum",'{"toggle_setting": "airplane_mode_on"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (8).png','common'::public."prank_rarity_enum"),
	 ('Temporary Gibberish Keyboard','Suddenly typing in Cyrillic or Greek letters for 1 minute.',40,22,8,8,3,'declarative'::public."prank_type_enum",'{"duration_seconds": 60, "keyboard_language_options": ["Cyrillic", "Greek", "Emoji-Only"]}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (17).png','rare'::public."prank_rarity_enum"),
	 ('Frozen Home Screen Illusion','My apps are frozen! I can''t click anything! (Screenshot home, set as wallpaper, hide all icons).',120,60,20,20,8,'declarative'::public."prank_type_enum",'{"action": "home_screen_freeze_illusion"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/extreme/card-extreme (2).png','extreme'::public."prank_rarity_enum"),
	 ('Hide Vital App','Where did my calculator app go? (Hides one frequently used app like Calculator or Weather).',33,19,6,7,2,'declarative'::public."prank_type_enum",'{"app_to_hide_options": ["Calculator", "Weather", "Notes"]}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (14).png','rare'::public."prank_rarity_enum");
INSERT INTO public.pranks ("name",description,default_jeton_cost_equivalent,xp_reward_executor,xp_reward_target,coins_reward_executor,coins_reward_target,"type",config_details_json,requires_proof,is_active,created_at,image_url,rarity) VALUES
	 ('Ghost Typer','Words magically appear on screen as they type or watch (Requires remote access or tricky timing).',150,70,25,25,10,'declarative'::public."prank_type_enum",'{"typing_speed": "slow", "message_to_type": "I see you..."}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/extreme/card-extreme (1).png','extreme'::public."prank_rarity_enum"),
	 ('Potato Appocalypse','My phone is now entirely potato-themed (Changes ALL app icons to pictures of potatoes).',130,65,22,22,9,'declarative'::public."prank_type_enum",'{"new_icon_theme": "potato_faces"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/extreme/card-extreme (3).png','extreme'::public."prank_rarity_enum"),
	 ('Fake Cuteness Virus Alert','Warning! Cuteness overload detected! Options: ''Embrace it'' or ''Try to resist'' (Full screen fake alert).',100,50,15,15,5,'notification_spam'::public."prank_type_enum",'{"body": "Your system has been infected with extreme cuteness. Recommended action: Awwee.", "title": "VIRUS: Cuteness Overload!", "options": ["Embrace it", "Try to Resist (Futility is Fun)"], "alert_type": "full_screen_modal"}',false,true,'2025-06-08 15:45:39.891114+02','assets/card/extreme/card-extreme (4).png','extreme'::public."prank_rarity_enum"),
	 ('Mysterious Jitters','My phone has the mysterious vibrating jitters (Continuously triggers short, random vibrations).',110,55,18,18,7,'declarative'::public."prank_type_enum",'{"duration_minutes": 5, "vibration_pattern": "random_short_bursts"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/extreme/card-extreme (5).png','extreme'::public."prank_rarity_enum"),
	 ('Robotic Notification Announcer','INCOMING MESSAGE FROM... MOM. MESSAGE READS... (Activates Text-to-Speech for ALL notifications in a robot voice).',140,68,24,24,9,'declarative'::public."prank_type_enum",'{"voice": "robot", "tts_setting": "all_notifications"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/extreme/card-extreme (6).png','extreme'::public."prank_rarity_enum"),
	 ('Fake Self-Destruct Sequence','10... 9... 8... (A fake phone self-destruct countdown timer appears, does nothing at zero).',100,50,15,15,5,'notification_spam'::public."prank_type_enum",'{"on_zero_action_message": "Just kidding! Gotcha!", "countdown_duration_seconds": 10}',false,true,'2025-06-08 15:45:39.891114+02','assets/card/extreme/card-extreme (7).png','extreme'::public."prank_rarity_enum"),
	 ('The Chosen One Autocorrect','Every time they type their name, it becomes "The Chosen One".',120,60,20,20,8,'declarative'::public."prank_type_enum",'{"replacement_text": "The Chosen One", "autocorrect_target": "user_name"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/extreme/card-extreme (8).png','extreme'::public."prank_rarity_enum"),
	 ('Snail Speed Animations','Opening apps now takes... for... ev... er (Slows down all phone animations to a crawl).',130,65,22,22,9,'declarative'::public."prank_type_enum",'{"animation_speed_multiplier": "0.1x"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/extreme/card-extreme (9).png','extreme'::public."prank_rarity_enum"),
	 ('App-Specific Record Scratch','Every time they open TikTok... SKRRRTCH! (Plays a sudden "record scratch" sound for a specific app opening).',110,55,18,18,7,'declarative'::public."prank_type_enum",'{"target_app": "TikTok", "sound_effect": "record_scratch.mp3"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/extreme/card-extreme (10).png','extreme'::public."prank_rarity_enum"),
	 ('Sock Gallery Invasion','Why do I have so many pictures of this one sock? (Fills gallery with 10 identical sock pics).',110,55,18,20,7,'declarative'::public."prank_type_enum",'{"action_description": "User must manually add 10 identical pictures of a single sock to the target''s photo gallery.", "proof_required_description": "Screenshot of gallery showing multiple sock pictures."}',true,true,'2025-06-08 16:11:08.524701+02','assets/card/extreme/card-extreme (11).png','extreme'::public."prank_rarity_enum");
INSERT INTO public.pranks ("name",description,default_jeton_cost_equivalent,xp_reward_executor,xp_reward_target,coins_reward_executor,coins_reward_target,"type",config_details_json,requires_proof,is_active,created_at,image_url,rarity) VALUES
	 ('Fake Fame Flood','My phone is blowing up with (fake) popularity! (Rapid-fire fake social/work notifications).',130,65,22,24,9,'notification_spam'::public."prank_type_enum",'{"burst_count": 5, "interval_ms": 500, "notifications": [{"body": "Your latest post is a hit!", "icon": "like_icon", "title": "New Like!"}, {"body": "@MysteriousFan just followed you!", "icon": "follower_icon", "title": "New Follower!"}, {"body": "URGENT: Need those reports ASAP!", "icon": "boss_icon", "title": "Message from Boss!"}, {"body": "InfluencerX wants to connect!", "icon": "friend_request_icon", "title": "Friend Request"}, {"body": "Your video is trending!", "icon": "trending_icon", "title": "Viral Alert!"}], "delivery_method": "rapid_burst"}',false,true,'2025-06-08 16:11:08.524701+02','assets/card/extreme/card-extreme (12).png','extreme'::public."prank_rarity_enum"),
	 ('Pocket Rave','Rave mode activated unexpectedly! (Screen flashes bright colors for 5 seconds).',100,50,16,18,6,'declarative'::public."prank_type_enum",'{"action_description": "User must find a way to make the target''s phone screen flash multiple bright colors rapidly for approximately 5 seconds (e.g., using an app, accessibility feature, or a quickly swiped full-screen color video).", "proof_required_description": "Video of the target''s phone screen flashing colors."}',true,true,'2025-06-08 16:11:08.524701+02','assets/card/extreme/card-extreme (13).png','extreme'::public."prank_rarity_enum"),
	 ('Malfunctioning AI Helper','A ''helpful'' AI starts giving hilariously wrong advice via notifications ("To make toast, preheat oven to 500°F and insert bread for 2 hours.").',125,62,20,22,8,'notification_spam'::public."prank_type_enum",'{"ai_name": "ClankyAI", "messages": ["ClankyAI: Reminder - The best way to sort socks is by throwing them all in one drawer.", "ClankyAI: To improve focus, try listening to three songs simultaneously.", "ClankyAI: For a healthy diet, ensure you eat at least one full-sized crayon daily.", "ClankyAI: Feeling stressed? Try screaming into a pillow. Your pillow loves it.", "ClankyAI: Pro tip: If your code doesn''t work, try adding more semicolons everywhere."], "total_messages": 5, "interval_minutes_between_messages": 15}',false,true,'2025-06-08 16:11:08.524701+02','assets/card/extreme/card-extreme (14).png','extreme'::public."prank_rarity_enum"),
	 ('Daily Sloth Facts Subscription','"Sign them up" for daily (fake) "Sloth Facts" notifications.',25,15,5,5,2,'notification_spam'::public."prank_type_enum",'{"sample_fact": "Sloths can hold their breath longer than dolphins!", "subscription_topic": "Daily Sloth Facts"}',false,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (15).png','rare'::public."prank_rarity_enum"),
	 ('Fake Critical Message Delivery Fail','Oh no, my crucial (fake) message about "Urgent: Free Pizza" didn''t send!',20,12,4,4,1,'notification_spam'::public."prank_type_enum",'{"error_message": "Message delivery failed. Recipient may be too cool.", "failed_message_subject": "Urgent: Free Pizza Tomorrow!"}',false,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (16).png','rare'::public."prank_rarity_enum"),
	 ('Compliment Barrage','You have excellent taste in memes! (Phone sends random, slightly off, or overly enthusiastic compliments via notification).',115,58,19,21,8,'notification_spam'::public."prank_type_enum",'{"compliments": ["Your ability to breathe is truly inspiring!", "You click buttons with such grace!", "The way you hold your phone is top-tier.", "Congratulations on existing today!", "Wow, your silence is incredibly profound right now!"], "total_compliments": 5, "interval_minutes_between_compliments": 10}',false,true,'2025-06-08 16:11:08.524701+02','assets/card/extreme/card-extreme (16).png','extreme'::public."prank_rarity_enum"),
	 ('Pirate Speak Phone','Ahoy, matey! Thy phone now be speakin'' like a proper pirate! (Changes phone language)',10,5,2,1,0,'declarative'::public."prank_type_enum",'{"target_language": "Pirate English"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (1).png','common'::public."prank_rarity_enum"),
	 ('Unlock Rickroll Surprise','Never gonna give you up... on pranking! (A Rick Astley video auto-opens once when the target unlocks their phone).',140,70,24,26,10,'declarative'::public."prank_type_enum",'{"video_url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "trigger_condition": "on_unlock_once", "action_description": "User must set up the target''s phone so that upon one specific unlock, a Rick Astley ''Never Gonna Give You Up'' video auto-plays (e.g., through an app, a browser tab left open and scripted, or a shortcut automation).", "proof_required_description": "Video of the target unlocking phone & Rickroll playing, or target''s confirmed reaction."}',true,true,'2025-06-08 16:11:08.524701+02','assets/card/extreme/card-extreme (17).png','extreme'::public."prank_rarity_enum"),
	 ('Fake System Update','A very official-looking (but fake) system update prompt appears.',5,3,1,0,0,'notification_spam'::public."prank_type_enum",'{"notification_body": "Tap to install critical security updates.", "notification_title": "System Update Required"}',false,true,'2025-06-08 15:45:39.891114+02','assets/card/common/card-common (3).png','common'::public."prank_rarity_enum"),
	 ('Whispering Meow Notifications','Did... did my phone just meow very softly? (Changes default notification sound to a tiny meow).',30,18,6,6,2,'declarative'::public."prank_type_enum",'{"new_notification_sound": "tiny_meow.mp3"}',true,true,'2025-06-08 15:45:39.891114+02','assets/card/rare/card-rare (13).png','rare'::public."prank_rarity_enum");
INSERT INTO public.pranks ("name",description,default_jeton_cost_equivalent,xp_reward_executor,xp_reward_target,coins_reward_executor,coins_reward_target,"type",config_details_json,requires_proof,is_active,created_at,image_url,rarity) VALUES
	 ('Absurd 8-Ball App','Ask it anything, get a nonsensical reply from a fake Magic 8-Ball app (e.g., Q: "Will I be rich?" A: "Ask your cat.").',105,52,17,19,7,'declarative'::public."prank_type_enum",'{"example_answers": ["Outlook... fluffy.", "Concentrate and ask again... after a nap.", "My sources say... maybe try interpretive dance?", "Cannot predict now, currently pondering the existential nature of cheese."], "action_description": "User must show the target a fake Magic 8-Ball app or website that gives absurd answers. The app could be one they create, find, or simulate via screenshots.", "proof_required_description": "Screenshot or short video of the fake 8-ball app giving an absurd answer to a question."}',true,true,'2025-06-08 16:11:08.524701+02','assets/card/extreme/card-extreme (15).png','extreme'::public."prank_rarity_enum");
